# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Project Gutenberg
email: webmaster2019@gutenberg.org
description: >- # this means to ignore newlines until "baseurl:"
  Project Gutenberg is a library of free eBooks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev.gutenberg.org/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gutenberg_org
github_username:  gbnewby

# Build settings
markdown: kramdown
### gbn: this is the default
### theme: minima
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - BACKUP
   - LICENSE
   - README.md
   - to_delete

destination: /public/vhost/g/gutenberg/dev/html/
timezone: America/New_York
encoding: utf-8 # default
incremental: TRUE # doesn't seem to work... all files are being built
keep_files: [.htaccess,cache,robots.txt,google3c00b5891470e2e3.html,catalog,browse,dirs,files,.acl.gutenwebdev,.acl.gutenwebprod,MIRRORS.ALL.utf8]
